version: "3.3"
services:
  nginx:
    image: nginx
    container_name: nginx
    depends_on:
      - node
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
  node:
    image: nextjs:latest
    container_name: navigator-front
  backend:
    image: backend:latest
    container_name: spring-boot
    depends_on: [postgres]
  postgres:
    image: postgres
    container_name: database
    ports:
      - "5432:5432"
    env_file:
      - ./.env.local
    volumes:
      - ./db:/docker-entrypoint-initdb.d