import "./globals.css";
import { Roboto } from "next/font/google";
import classNames from "classnames";
import React from "react";
import { Header } from "@/widgets/header";
import { Footer } from "@/widgets/footer";

const roboto = Roboto({
  subsets: ["cyrillic-ext"],
  weight: ["400", "700"],
  style: ["normal", "italic"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body
        className={classNames(
          roboto.className,
          "flex min-h-screen flex-col gap-5 bg-body-back"
        )}
      >
        <Header />
        <main className='flex flex-grow flex-col gap-2'>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
